name: compsci371
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python
  - notebook
  - nbconvert
  - jupytext
  - numpy
  - scikit-image
  - scikit-learn
  - scipy
  - tqdm
  - matplotlib
  - pytorch
  - torchvision
  - autograd
